force-app/main/default/objects/APEX_Customer__c/APEX_Customer__c.object-meta.xml
<CustomObject>
    <description>Information related to the customers.</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Invoice__c/APEX_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Invoice__c/fields/APEX_Status__c.field-meta.xml
<CustomField>
    <fullName>APEX_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerTriggerHelper.cls
public class CustomerTriggerHelper {
    public static void isAfterUpdateCall(List<APEX_Customer__c> customerList, Map<Id, APEX_Customer__c> oldMapCustomer) {
        createInvoiceRecords(customerList, oldMapCustomer);
        updateInvoiceDesc(customerList);           
    }
    public static void createInvoiceRecords(List<APEX_Customer__c> customerList, Map<Id, APEX_Customer__c> oldMapCustomer) {
        List<APEX_Invoice__c> invoiceList = new List<APEX_Invoice__c>();
        For(APEX_Customer__c cus:CustomerList) {
            if(cus.APEX_Customer_Status__c == 'Active' && OldMapCustomer.get(cus.Id).APEX_Customer_Status__c == 'Inactive') {
                APEX_Invoice__c inv = new APEX_Invoice__c();
                inv.APEX_Status__c = 'Unpaid';
                inv.APEX_Customer__c = cus.Id;
                invoiceList.add(inv);                
            }
        }
        Insert invoiceList;
    }
    public static void updateInvoiceDesc(List<APEX_Customer__c> customerList) {
        List<APEX_Invoice__c> updateInvoices = new List<APEX_Invoice__c>();
        List<APEX_Invoice__c> invoices = [SELECT Id, Name, APEX_Description__c
                                          FROM APEX_Invoice__c
                                          WHERE APEX_Customer__c IN: customerList];
        For(APEX_Invoice__c invoice:invoices) {
                invoice.APEX_Description__c = 'Updated through the trigger';
                updateInvoices.add(invoice);
            }
        Update updateInvoices;
        }   
              
    }